apiVersion: apps/v1
kind: Deployment
metadata:
  name: windmill-app
  labels:
    app: windmill-app
    app.kubernetes.io/name: windmill-app
    chart: {{ template "windmill.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.windmill.appReplicas }}
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 0
  selector:
    matchLabels:
      app: windmill-app
  template:
    metadata:
      labels:
        app: windmill-app
        app.kubernetes.io/name: windmill-app
        release: {{ .Release.Name }}
{{- with .Values.windmill.app.annotations }}
      annotations:
{{ toYaml . | indent 8 }}       
{{- end }}  
    spec:
      {{ if windmill.serviceAccountName  }}
      serviceAccountName: {{ windmill.serviceAccountName }}
      {{ end }}
      terminationGracePeriodSeconds: 40
      containers:
      - name: windmill-app
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 30"]
        volumeMounts:
        - name: oauth-volume
          mountPath: /usr/src/app/oauth.json
          subPath: oauth.json
          readOnly: true
        {{ if .Values.enterprise.enabled }}
        image: ghcr.io/windmill-labs/windmill-ee:{{ default .Chart.AppVersion .Values.windmill.tag }}
        {{ else }}
        image: ghcr.io/windmill-labs/windmill:{{ default .Chart.AppVersion .Values.windmill.tag }}
        {{ end }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        - containerPort: 8001
        readinessProbe:
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 1
          httpGet:
            host:
            scheme: HTTP
            path: /
            httpHeaders:
            - name: Host
              value: localhost
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name : "METRICS_ADDR"
          value: "true"
        - name: "DATABASE_URL"
          value: "{{ .Values.windmill.databaseUrl }}"
        - name: "BASE_URL"
          value: "{{ .Values.windmill.baseProtocol }}://{{ .Values.windmill.baseDomain }}"
        - name: "RUST_LOG"
          value: "{{ .Values.windmill.rustLog }}"
        - name: "NUM_WORKERS"
          value: "0"
        - name: "JSON_FMT"
          value: "true"
        {{ if .Values.windmill.instanceEventsWebhook }}
        - name: "INSTANCE_EVENTS_WEBHOOK"
          value: "true"
        {{ end }}
        {{ if .Values.enterprise.enabled }}
        - name: "LICENSE_KEY"
          value: "{{ .Values.enterprise.licenseKey }}"
        {{ end }}
        - name: "CUSTOM_TAGS"
          value: "{{- range $v := .Values.windmill.workerGroups }}{{ $v.name }},{{ end}}"
        resources:
  {{ toYaml .Values.windmill.app.resources | indent 12 }}
      volumes:
      - name: oauth-volume
        secret:
          secretName: {{ if .Values.windmill.oauthSecretName }}{{ .Values.windmill.oauthSecretName }}{{ else }} {{ .Release.Name }}-oauth-secret {{- end }}
    {{- with .Values.windmill.app.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.windmill.app.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.windmill.app.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      securityContext:
        runAsUser: 0
---
apiVersion: v1
kind: Service
metadata:
  name: windmill-app
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app.kubernetes.io/name: windmill-app
  sessionAffinity: ClientIP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: windmill-app-metrics
  labels:
    operated-prometheus: "true"
spec:
  clusterIP: None
  ports:
  - port: 8001
    name: metrics
    protocol: TCP
  selector:
    app.kubernetes.io/name: windmill-app
  sessionAffinity: None
  type: ClusterIP
# ---
# apiVersion: monitoring.coreos.com/v1
# kind: ServiceMonitor
# metadata:
#   name: windmill-app
#   labels:
#     instance: primary
# spec:
#   selector:
#     matchLabels:
#       app: windmill-app-metrics
#   endpoints:
#   - port: metrics
#     interval: 30s
#     path: /metrics